shows = {
  'https://www.crunchyroll.com/my-hero-academia/reviews/helpful/page': [],
  'https://www.crunchyroll.com/black-clover/reviews/helpful/page': [],
  'https://www.crunchyroll.com/dr-stone/reviews/helpful/page': [],
  'https://www.crunchyroll.com/boruto-naruto-next-generations/reviews/helpful/page': [],
  'https://www.crunchyroll.com/food-wars-shokugeki-no-soma/reviews/helpful/page': [],
  'https://www.crunchyroll.com/welcome-to-demon-school-iruma-kun/reviews/helpful/page': [],
  'https://www.crunchyroll.com/fire-force/reviews/helpful/page': [],
  'https://www.crunchyroll.com/sword-art-online/reviews/helpful/page': [],
  'https://www.crunchyroll.com/naruto-shippuden/reviews/helpful/page': [],
  'https://www.crunchyroll.com/rezero-starting-life-in-another-world-/reviews/helpful/page': [],
  'https://www.crunchyroll.com/jojos-bizarre-adventure/reviews/helpful/page': [],
  'https://www.crunchyroll.com/that-time-i-got-reincarnated-as-a-slime/reviews/helpful/page': [],
  'https://www.crunchyroll.com/demon-slayer-kimetsu-no-yaiba/reviews/helpful/page': [],
  'https://www.crunchyroll.com/hunter-x-hunter/reviews/helpful/page': [],
  'https://www.crunchyroll.com/radiant/reviews/helpful/page': [],
  'https://www.crunchyroll.com/keep-your-hands-off-eizouken/reviews/helpful/page': [],
   'https://www.crunchyroll.com/assassins-pride/reviews/helpful/page': [],
  'https://www.crunchyroll.com/room-camp/reviews/helpful/page': [],
  'https://www.crunchyroll.com/high-school-prodigies-have-it-easy-even-in-another-world/reviews/helpful/page': []
}